### ISSUE TITLE
Contains() function is void

### ISSUE THREAD

**Issue by IIInitiationnn** [cdanek/kaimira-weighted-list#6]
Thanks for your work developing this awesome little utility!
While not a huge issue to remedy, I noticed that the `Contains` function is currently void:

```c#
public void Contains(T item) => _list.Contains(item);
```
which can be easily replaced with
```c#
public bool Contains(T item) => _list.Contains(item);
```

**Comment by cdanek** [comment]
Thanks, nice catch! Updated.
